#!/bin/sh

set -eux

version=$(git describe --long --tags)
base="${2##*/git-get-}"
os="${base%-*}"
arch="${base#*-}"
CGO_ENABLED=0 GOARCH="$arch" GOOS="$os" go build -v -a -tags netgo -o "$1" -ldflags "-X main.version=${version}" ./...
