#!/bin/sh

set -eux
version=$(git describe --long --tags)
name="${2#*/}"
os="${name%%-*}"
release="${2%/*}"
arch="${release##*-}"
GOARCH="$arch" GOOS="$os" go build -o "$1" -ldflags "-X main.version=${version}" ./...
